import { getLocalSong, isLocalTrackId } from '@/services/local-music';
import { getAudiusTrack } from '@/services/audius';
import type { CrimsonPlaylist, CrimsonSong } from '@/types/music';

const oldMixPlaceholder = (playlist: CrimsonPlaylist) => Boolean(playlist.artworkIsAutoGenerated && /\[Crimson mix [a-z-]+ [\d-]+\]/.test(playlist.description || ''));

export function playlistArtworkFromSongs(playlist: CrimsonPlaylist, songs: (CrimsonSong | null)[]): CrimsonPlaylist {
  if ((playlist.image || playlist.imageSmall) && !oldMixPlaceholder(playlist)) return playlist;
  return {
    ...playlist,
    ...(oldMixPlaceholder(playlist) ? { image: '', imageSmall: '' } : {}),
    coverImages: songs.flatMap((song) => song?.image ? [song.image] : song?.imageSmall ? [song.imageSmall] : []).slice(0, 4),
    coverImagesSmall: songs.flatMap((song) => song?.imageSmall ? [song.imageSmall] : song?.image ? [song.image] : []).slice(0, 4),
  };
}

/** Hydrate only visible picker rows; existing custom artwork always wins. */
export async function playlistPickerArtwork(playlist: CrimsonPlaylist): Promise<CrimsonPlaylist> {
  if (((playlist.image || playlist.imageSmall) && !oldMixPlaceholder(playlist)) || playlist.coverImages?.length || !playlist.songs.length) return playlist;
  const covers = await Promise.all([...new Set(playlist.songs)].slice(0, 4).map((id) => (isLocalTrackId(id) ? getLocalSong(id) : getAudiusTrack(id)).catch(() => null)));
  return playlistArtworkFromSongs(playlist, covers);
}
